name: JourneyFlutter
repository: https://github.com/tryjourney/journey-flutter

packages:
  - packages/*

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    exec: dart analyze --fatal-warnings --fatal-infos .

  format:
    exec: dart format lib test -l 80 --set-exit-if-changed

  upgrade:
    exec: dart pub upgrade

  outdated:
    exec: dart pub outdated